// <auto-generated />
using System;
using Investimentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investimentos.Migrations
{
    [DbContext(typeof(InvestimentosContext))]
    [Migration("20220121163105_TodasEntidades")]
    partial class TodasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Investimentos.Models.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PapelId");

                    b.Property<double>("PrecoMedio");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("PapelId");

                    b.ToTable("Carteira");
                });

            modelBuilder.Entity("Investimentos.Models.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("C_V")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<DateTime>("DataOperacao");

                    b.Property<string>("Negociacao");

                    b.Property<string>("Obs");

                    b.Property<int>("PapelId");

                    b.Property<double>("Preco");

                    b.Property<int>("Quantidade");

                    b.Property<string>("TipoMercado");

                    b.Property<double>("ValorOperacao");

                    b.HasKey("Id");

                    b.HasIndex("PapelId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("Investimentos.Models.Papel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int>("TipoPapelId");

                    b.HasKey("Id");

                    b.HasIndex("TipoPapelId");

                    b.ToTable("Papel");
                });

            modelBuilder.Entity("Investimentos.Models.TipoPapel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("TipoPapel");
                });

            modelBuilder.Entity("Investimentos.Models.Carteira", b =>
                {
                    b.HasOne("Investimentos.Models.Papel", "Papel")
                        .WithMany()
                        .HasForeignKey("PapelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Investimentos.Models.Historico", b =>
                {
                    b.HasOne("Investimentos.Models.Papel", "Papel")
                        .WithMany()
                        .HasForeignKey("PapelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Investimentos.Models.Papel", b =>
                {
                    b.HasOne("Investimentos.Models.TipoPapel", "TipoPapel")
                        .WithMany()
                        .HasForeignKey("TipoPapelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
