// <auto-generated />
using Investimentos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investimentos.Migrations
{
    [DbContext(typeof(InvestimentosContext))]
    [Migration("20220120224234_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Investimentos.Models.Papel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int>("TipoPapelId");

                    b.HasKey("Id");

                    b.HasIndex("TipoPapelId");

                    b.ToTable("Papel");
                });

            modelBuilder.Entity("Investimentos.Models.TipoPapel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("TipoPapel");
                });

            modelBuilder.Entity("Investimentos.Models.Papel", b =>
                {
                    b.HasOne("Investimentos.Models.TipoPapel", "TipoPapel")
                        .WithMany()
                        .HasForeignKey("TipoPapelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
